import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillInstagram,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import logo from "../public/logo.png";
/* import design from "..public/Coding-Html-icon.png";
import code from "..public/design.png";
import consulting from "..public/consulting.png"; */

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mario M. Elizalde Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-Playfair">DevelopedBymarioeBros</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-green-500 to-orange-600 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-orange-500 font-medium">
              Mario M. Elizalde
            </h2>
            <h3 className="text-2xl py-2">Software Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800">The Man.</p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-800">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillInstagram />
            <AiFillGithub />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-orange-600 rounded-full w-80 h-80 mt-20">
            <Image
              className="bg-opacity-0"
              src={logo}
              layout="fill"
              objectFit="cover"
            />
          </div>
        </section>

        {/* Page II */}

        <section>
          <div>
            <h3 className="text-3xl py-1">Services I Offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Since beginning my journey as a freelance developer, I've
              completed remote courses in{" "}
              <span className="text-orange-600">
                Web Programming Foundations,{" "}
              </span>
              <span className="text-orange-600">HTML, CSS, & JavaScript, </span>
              <span className="text-orange-600">
                React, Next.js, & jQuery,{" "}
              </span>
              <span className="text-orange-600">
                Solidity, Smart Contracts, & Cryptography.
              </span>
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              I offer a range of services including...
            </p>
          </div>
          <div>
            <div>{/* <Image src={design} /> */}</div>
          </div>
        </section>
      </main>
    </div>
  );
}
